controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


  wheel_controller:
    type: chassis_controller/ChassisController
    fl_pid_follow: { p: 61, i: 0, d: 0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    fr_pid_follow: { p: 61, i: 0, d: 0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    bl_pid_follow: { p: 61, i: 0, d: 0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    br_pid_follow: { p: 61, i: 0, d: 0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }


#  fl_velocity_controller:
#    type: effort_controllers/JointVelocityController
#    joint: front_left_wheel_joint
#    pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true }


