footprint: [[-0.5, -0.55], [-0.5, 0.55], [0.5, 0.55], [0.5, -0.55]]


obstacle_range: 3.0
raytrace_range: 3.5


#layer definitions
static:
  map_topic: map
  subscribe_to_updates: truefootprint_model

obstacles_laser:
  observation_sources: realsense
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: front/scan, inf_is_valid: true}
  realsense: {data_type: PointCloud2, clearing: true, marking: true, topic: /d435/depth/color/points, inf_is_valid: true}

inflation:
  inflation_radius: 0.2
