global_costmap:
  global_frame: map
  static_map: true
  track_unknown_space: true

  update_frequency: 1.0 #代价地图更新频率
  publish_frequency: 1.0 #代价地图的发布频率
  transform_tolerance: 0.5 #等待坐标变换发布信息的超时时间
  robot_base_frame: base_link

  resolution: 0.05

  plugins:
    - {name: static,                  type: "costmap_2d::StaticLayer"}
    - {name: inflation,               type: "costmap_2d::InflationLayer"}

