TebLocalPlannerROS:

    #Robot Footprint Parameters
    type: circular
    radius: 0.5

    #Trajectory Configuration
    teb_autosize: true
    global_plan_overwrite_orientation: true
    max_samples: 10
    min_samples: 2

    #Robot Configuration Parameters
    max_vel_x: 3.0
    max_vel_x_backwards: 3.0
    max_vel_theta: 2.0
    acc_lim_x: 1.0
    acc_lim_theta: 1.0

    #Goal Tolerance Parameters
    xy_goal_tolerance: 0.3
    yaw_goal_tolerance: 0.2
    free_goal_vel: true

    #Obstacle Parameters
    min_obstacle_dist: 0.2
    include_costmap_obstacles: true
    costmap_obstacles_behind_robot_dist: 0.1

    #Optimization Parameters
    optimization_activate: true
    optimization_verbose: true

    #Homotopy Parameters
    enable_multithreading: true
    max_number_classes: 3