//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : simple_state.sm
//


//
// a simple state machine,for learning and testing
//


#include "chassis_controller/EasyStateMachine.h"
#include "EasyStateMachine_sm.h"

using namespace statemap;

// Static class declarations.
EasyStateMachineMap_Safe EasyStateMachineMap::Safe("EasyStateMachineMap::Safe", 0);
EasyStateMachineMap_Danger EasyStateMachineMap::Danger("EasyStateMachineMap::Danger", 1);

void EasyStateMachineState::processState(EasyStateMachine_sm& context)
{
    Default(context);
}

void EasyStateMachineState::Default(EasyStateMachine_sm& context)
{
    throw (
        TransitionUndefinedException(
            context.getState().getName(),
            context.getTransition()));

}

void EasyStateMachineMap_Default::processState(EasyStateMachine_sm& context)
{


}

void EasyStateMachineMap_Safe::Entry(EasyStateMachine_sm& context)

{
    EasyStateMachine& ctxt = context.getOwner();

    ctxt.hp_reduce();
    ctxt.move_forward();
}

void EasyStateMachineMap_Safe::processState(EasyStateMachine_sm& context)
{

    if (hp<=500)
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(EasyStateMachineMap::Danger);
        context.getState().Entry(context);
    }
    else
    {
         EasyStateMachineMap_Default::processState(context);
    }

}

void EasyStateMachineMap_Danger::Entry(EasyStateMachine_sm& context)

{
    EasyStateMachine& ctxt = context.getOwner();

    ctxt.hp_increase();
    ctxt.move_back();
}

void EasyStateMachineMap_Danger::processState(EasyStateMachine_sm& context)
{

    if (hp>500)
    {
        context.getState().Exit(context);
        // No actions.
        context.setState(EasyStateMachineMap::Safe);
        context.getState().Entry(context);
    }
    else
    {
         EasyStateMachineMap_Default::processState(context);
    }

}

//
// Local variables:
//  buffer-read-only: t
// End:
//
